### ISSUE TITLE
[WEEK1] Data Structre (자료구조)

### ISSUE THREAD

**Issue by sunnyineverywhere** [sunnyineverywhere/algorithm#2]
`기한` 23. 05. 31 - 23. 06. 06

|          순번          |        추천 문제         |        문제 번호         |        문제 이름         |         난이도          |
| :-----: | :-----: | :-----: | :-----: | :-----: |
| 00 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/10828" target="_blank">10828</a> | <a href="https://www.acmicpc.net/problem/10828" target="_blank">스택</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 01 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/9012" target="_blank">9012</a> | <a href="https://www.acmicpc.net/problem/9012" target="_blank">괄호</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 02 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/18258" target="_blank">18258</a> | <a href="https://www.acmicpc.net/problem/18258" target="_blank">큐 2</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 03 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/1158" target="_blank">1158</a> | <a href="https://www.acmicpc.net/problem/1158" target="_blank">요세푸스 문제</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 04 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/2164" target="_blank">2164</a> | <a href="https://www.acmicpc.net/problem/2164" target="_blank">카드2</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 05 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/10866" target="_blank">10866</a> | <a href="https://www.acmicpc.net/problem/10866" target="_blank">덱</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/7.svg"/> |
| 06 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/1935" target="_blank">1935</a> | <a href="https://www.acmicpc.net/problem/1935" target="_blank">후위 표기식2</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/8.svg"/> |
| 07 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/1966" target="_blank">1966</a> | <a href="https://www.acmicpc.net/problem/1966" target="_blank">프린터 큐</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/8.svg"/> |
| 08 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/2346" target="_blank">2346</a> | <a href="https://www.acmicpc.net/problem/2346" target="_blank">풍선 터뜨리기</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/8.svg"/> |
| 09 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/1874" target="_blank">1874</a> | <a href="https://www.acmicpc.net/problem/1874" target="_blank">스택 수열</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/9.svg"/> |
| 10 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/10799" target="_blank">10799</a> | <a href="https://www.acmicpc.net/problem/10799" target="_blank">쇠막대기</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/9.svg"/> |
| 11 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/2504" target="_blank">2504</a> | <a href="https://www.acmicpc.net/problem/2504" target="_blank">괄호의 값</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/10.svg"/> |
| 12 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/2800" target="_blank">2800</a> | <a href="https://www.acmicpc.net/problem/2800" target="_blank">괄호 제거</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/11.svg"/> |
| 13 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/2493" target="_blank">2493</a> | <a href="https://www.acmicpc.net/problem/2493" target="_blank">탑</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/11.svg"/> |
| 14 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/22942" target="_blank">22942</a> | <a href="https://www.acmicpc.net/problem/22942" target="_blank">데이터 체커</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/12.svg"/> |
| 15 |  :heavy_check_mark:  | <a href="https://www.acmicpc.net/problem/1918" target="_blank">1918</a> | <a href="https://www.acmicpc.net/problem/1918" target="_blank">후위 표기식</a> | <img height="25px" width="25px" src="https://static.solved.ac/tier_small/14.svg"/> |

**Comment by sunnyineverywhere** [comment]
풀이 : 14, 15

**Comment by yhjune** [comment]
풀이 : 12, 13
